spring:
  jackson:
    date-format:   'yyyy-MM-dd HH:mm:ss'
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**

  datasource:
    url: 'jdbc:mysql://192.168.100.8:5509/pro_new_emergency?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false'
    username: root
    password: suncompass
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  kafka:
    bootstrap-servers: 112.74.56.201:9002
    consumer:
      # 默认消费者group id
      group-id: user-log-group
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
      #避免consumer保证数据不丢失，关闭自动提交offset
      enable-auto-commit: false
      auto-commit-interval: 100
    producer:
      retries: 3  #  重试次数
      # 每次批量发送消息的数量
      batch-size: 16384
      # buffer.memory 控制生产者可用的缓存总量，如果消息发送速度比其传输到服务器的快，将会耗尽这个缓存空间。
      buffer-memory: 33554432
      # 指定消息value和消息体的编解码方式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    com.chuansen: debug


