spring:
  jackson:
    date-format:   'yyyy-MM-dd HH:mm:ss'
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**

logging:
  level:
    com.chuansen: debug

#===ElasticSearch===
elasticsearch:
  hostname: '127.0.0.1'
  index:
    name: 'pro_new_emergency'
